# Generated by Django 5.0.6 on 2024-07-16 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='location_images/no-image-available-building.jpg', null=True, upload_to='location_images/')),
            ],
        ),
        migrations.CreateModel(
            name='RentalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('car', 'Car'), ('motorcycle', 'Motorcycle'), ('construction_equipment', 'Construction Equipment')], max_length=30)),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('number_plate', models.CharField(default='XX-XX-XX', max_length=12, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, default='rental_images/no-photo.jpg', null=True, upload_to='rental_images/')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motionRent.location')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('rental_date', models.DateField()),
                ('return_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rental_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motionRent.rentalitem')),
            ],
        ),
    ]
