# Generated by Django 5.0.6 on 2024-07-16 17:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motionRent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
