# Generated by Django 5.0.6 on 2024-07-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motionRent', '0002_rentalitem_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalitem',
            old_name='type',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='image',
            field=models.ImageField(blank=True, default='rental_images/no-photo.jpg', null=True, upload_to='rental_images/'),
        ),
    ]
