# Generated by Django 5.0.6 on 2024-07-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motionRent', '0002_rental_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='drivers_license',
            field=models.CharField(default='XX-XX-XX', max_length=50),
        ),
    ]
